# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 644390c8adc3fa98f0d401baaca5cc0efe6d6ed9f6e8ba69274e76475b27ff4e6b311180bdeb466e0fa8caa070257d621f5a67c590c1494a70ee6f903751380b

test:
  secret_key_base: 685c7d57b65b8707b5322b83ad53f5c597c14223868176c3dcc49e1333b099198160e95362b4be73c1266f38c7371a2cfad4cb0741220fabbb1ed8c476bf63b8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
